from . import route_area
from . import route_outlet
from . import route_plan
from . import route_plan_line
from . import route_vehicle
from . import route_visit
from . import sale_order
from . import route_visit_line
from . import route_visit_payment
from . import outlet_stock_balance
from . import route_visit_ext
from . import route_outlet_ext
from . import route_refill_backorder
from . import route_refill_backorder_line
from . import route_plan_pda
from . import route_vehicle_location_ext
from . import route_outlet_location_ext
from . import route_visit_stock_ext
from . import stock_picking_route_visit_ext
from . import route_visit_picking_ext
from . import stock_move_route_visit_ext
from . import route_visit_move_ext
from . import route_visit_load_balance_ext
from . import route_visit_line_vehicle_ext
from . import route_visit_scan_ext
from . import route_visit_workflow_ux
