{
    "name": "Route Core",
    "version": "19.0.1.0.33",
    "summary": "Sales representative route visits",
    "author": "Yasser Fayed",
    "license": "LGPL-3",
    "depends": ["base", "sale", "mail", "stock", "contacts"],
    "data": [
        "security/route_security_groups.xml",
        "security/ir.model.access.csv",
        "security/route_record_rules.xml",
        "security/route_vehicle_closing_pending_visit_security.xml",
        "security/route_plan_skip_visit_security.xml",
        "security/route_plan_pending_visit_review_security.xml",
        "data/route_visit_sequence.xml",
        "data/route_outlet_sequence.xml",
        "data/route_vehicle_sequence.xml",
        "data/route_plan_sequence.xml",
        "data/route_refill_backorder_sequence.xml",
        "data/route_shortage_sequence.xml",
        "data/route_loading_proposal_sequence.xml",
        "data/route_vehicle_closing_sequence.xml",
        "data/route_salesperson_shortage_sequence.xml",
        "data/route_salesperson_deduction_sequence.xml",
        "data/route_direct_return_sequence.xml",
        "views/route_city_views.xml",
        "views/route_area_views.xml",
        "views/route_outlet_views.xml",
        "views/route_plan_views.xml",
        "views/route_vehicle_views.xml",
        "views/route_return_settings_views.xml",
        "views/route_visit_views.xml",
        "views/route_visit_payment_views.xml",
        "views/route_visit_workflow_ux_views.xml",
        "views/route_visit_payment_ux_views.xml",
        "views/outlet_stock_balance_views.xml",
        "views/route_location_link_views.xml",
        "views/route_product_barcode_views.xml",
        "views/route_shortage_views.xml",
        "views/route_loading_proposal_views.xml",
        "views/route_vehicle_stock_snapshot_views.xml",
        "views/route_vehicle_closing_views.xml",
        "views/route_salesperson_deduction_views.xml",
        "reports/route_salesperson_shortage_report.xml",
        "views/route_salesperson_shortage_views.xml",
        "views/route_visit_document_links_views.xml",
        "views/route_direct_return_views.xml",
        "views/route_pda_home_views.xml",
        "views/sale_order_direct_sale_views.xml",
        "views/route_role_actions_menus.xml",
        "views/route_role_ui_security_views.xml",
        "wizard/route_visit_end_wizard_views.xml",
        "wizard/route_plan_add_area_outlets_wizard_views.xml",
        "wizard/route_plan_skip_visit_wizard_views.xml",
        "wizard/route_visit_scan_wizard_views.xml",
        "wizard/route_visit_return_scan_wizard_views.xml",
        "wizard/route_visit_collect_payment_wizard_views.xml",
        "wizard/route_visit_missing_lot_wizard_views.xml",
        "wizard/route_loading_source_wizard_views.xml",
        "wizard/route_vehicle_closing_scan_wizard_views.xml",
        "wizard/route_vehicle_closing_pending_visit_wizard_views.xml",
        "wizard/route_plan_pending_visit_review_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "route_core/static/src/js/route_visit_scan_focus.js",
            "route_core/static/src/css/route_pda_home.css",
        ],
    },
    "installable": True,
    "application": True,
}
