{
    "name": "Route Core",
    "version": "19.0.1.0.1",
    "summary": "Sales representative route visits",
    "author": "Yasser Fayed",
    "license": "LGPL-3",
    "depends": ["base", "sale", "mail", "stock", "contacts"],
    "data": [
        "security/ir.model.access.csv",
        "data/route_visit_sequence.xml",
        "data/route_outlet_sequence.xml",
        "data/route_vehicle_sequence.xml",
        "data/route_plan_sequence.xml",
        "data/route_refill_backorder_sequence.xml",
        "views/route_area_views.xml",
        "views/route_outlet_views.xml",
        "views/route_plan_views.xml",
        "views/route_vehicle_views.xml",
        "views/route_return_settings_views.xml",
        "views/route_visit_views.xml",
        "views/route_visit_payment_views.xml",
        "views/route_visit_workflow_ux_views.xml",
        "views/route_visit_payment_ux_views.xml",
        "views/outlet_stock_balance_views.xml",
        "views/route_location_link_views.xml",
        "views/route_product_barcode_views.xml",
        "wizard/route_visit_end_wizard_views.xml",
        "wizard/route_plan_add_area_outlets_wizard_views.xml",
        "wizard/route_visit_scan_wizard_views.xml",
        "wizard/route_visit_return_scan_wizard_views.xml",
        "wizard/route_visit_collect_payment_wizard_views.xml",
        "wizard/route_visit_missing_lot_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "route_core/static/src/js/route_visit_scan_focus.js",
        ],
    },
    "installable": True,
    "application": True,
}
